apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:qwerty12345@ecommerce-ms-postgres-dev.c05y8cmq8lex.us-east-1.rds.amazonaws.com:5432/ecommerce"
  GCP_SERVICE_ACCOUNT_KEY: |
    {
      "type": "service_account",
      "project_id": "cloud-computing-479420",
      "private_key_id": "3fc5e2cbc971274fe2f408a7d5ff8888710dbc23",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCs93wC5OOWSpDy\n+vhQQgjwep3riVYts2M9pDA4e4av2mJYl2EcyKlxYQCeymf1DMgvvQe7qiTHEB+M\nFnRskIkjlmELocPx0xwAjZxM9vDcKrlbtwRkffGKnI+wyYH9tHUqnif0pIqYf/4g\nHfxur0jaTRnTTwRmC2EvhqmBVX/TUfIDLdKbYsTg2NAIBQOhTyzWYCcTcJ8/l12k\nlx3R4+54qfbbjpDVwhs9IulbgM1nbRLhWr9EOzY4G5uXsDHRETPZEcC8C3ePxwAL\nj7Ufec1/1YVX3Z5NJxgo1SNNp3mX71KGhEkuV8BGNaQYcQbprSdcJUxck48Kv6Ji\n3zKa5lv5AgMBAAECggEAHshWvi8dH+C6ZjvrGGGANMgltcb12uFLnqtLV6oIQOC1\nUv3x7wz5Nu/kC96K3M4/DFvwdeIkdHb2nlhatP2OIpK/R7Is7Ks9Fw4czIfAOvax\nkVSDiBzv8VLGsdhS9aN5nLGT+9KSxew1fmLHy60PYqaJG5W6+yw4ShyFqzpbqvBl\nsFqQ0au1R/5z/AtXi/CFSvDeEaoZWZJm61B6VgF9xQNCpSZjQyADPR3Wh+QEvyMA\n+0F0FyIc8A8lNJ6kdyJ1tGrfmjRdd63CeyAMDnKc+kp4HB5zsT6AvzFzboYEFtPG\n7OezBFHvzc7zpFb/MNZ+Taap8yokG396IOBsz0pDxwKBgQDqurz7SMdjpMTlmoNC\nT6W3jScp5Iq7aQD2KcXhfL3d6BVEcBj7BkruXUJwPXbNKUSbrf0nWcERUFOonPoR\na9JTSSQTMV8v1GMLVDeuYKCB3J8LngaYJlabM30qr76SUOuCl3Wx2RjNOwCGkk3X\n5FcMCRpUfdPSoweRxHajF5opHwKBgQC8o/kEy6HSppcasXmkoC6urtpjrvc1ESnS\n2T5OmCmGzY3S0XRpsWlci2TotgiVDWd9Mqz2tgEHb3HhzG+Ji9KCKb53LwmR4pYH\nVNCkXvvPxYJMwwj+oT2YizHgUe9jBzwM78Gx96sLaZ1cwIpJnY7t2q/u7gMq77N2\nv/S+W5+f5wKBgQCql9jtD7HJm2B2Nlua/+PCiNWjvrONDP1j6mwkOtKKyjdaq9Wb\n6rDel+zHQgRrisiQFF1eEf8dJDII4z1jF+eeHBQZ1tIFIuhwvV5SX2uHtd3pRYop\nXgOnfD5FncB0+laPbKBfBxbdYTo6k237r7oLxznZmjEubsn7iLtoQKkLpQKBgQCs\n5g3D23CCxrYQfUJlJXwkF5eLbj6eoRCYdQ2qs8S8DYNECz6L8VQEwq7GrLHJC/Qi\nyGPH7KGc0wSqVNqWU1Wqf+BXFQHMeMXSCmcBgR2EHh+Dg++mktsGCe65D+A9/8+G\ne+oo2Dwpxa+556/YMVVjpOFEOVsl63WuDdqg7xGrWQKBgAu8iP/YGxC/QceO0FGt\nsYfUZzjoRCJPNx616evABAfguNW+V/gj2J9FaBNSFGZZWO9SEGTZ91bpEWHGdSbq\nMVqYUuyz4YblDY4Az/AkKBZRCXfOhCHVvi9fsjImu550RWCTqUyRj2cHrgOKcMCj\nEZ30SrEWSuN/sM49aZIkNIKS\n-----END PRIVATE KEY-----\n",
      "client_email": "order-service@cloud-computing-479420.iam.gserviceaccount.com",
      "client_id": "112929645096392751786",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/order-service%40cloud-computing-479420.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
