apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:qwerty12345@ecommerce-ms-postgres-dev.c05y8cmq8lex.us-east-1.rds.amazonaws.com:5432/ecommerce"
  KAFKA_BOOTSTRAP_SERVERS: "b-1.ecommercemskafkadev.xoty62.c2.kafka.us-east-1.amazonaws.com:9096,b-2.ecommercemskafkadev.xoty62.c2.kafka.us-east-1.amazonaws.com:9096"
  KAFKA_USERNAME: "kafka-admin"
  KAFKA_PASSWORD: "KafkaPassword123!"
